### ISSUE TITLE
Super

### ISSUE THREAD

**Issue by AleksandarTheBoulderRankovic** [gianthead97/borjan_borjan_skocko_pik#1]
Imam mali problem da su mi svi igraci isti osim jednog koji je erm druge boje... Takodje mi se cetvrti kruzic prikazuje u novom redu tako da posle cetvrtog pokusaja ne vidim sta se desava i da li sam ista pogodio

**Comment by gianthead97** [comment]
Igrica nije zamišljenja da je igraju noobovi.
